---

- block:

    - name: Make sure the folder exists
      file:
        path: /etc/pki/ca-trust/source/anchors
        state: directory

    - name: Copy PEM into folder
      copy:
        src: '{{ common_ca }}'
        dest: /etc/pki/ca-trust/source/anchors/{{ common_ca | basename }}
      register: result

    - name: Update CA Trust
      command: update-ca-trust
      when: result is changed

    - name: Update CA Trust
      command: update-ca-trust enable
      when:
        - result is changed
        - ansible_distribution_version | int < 7

  when: ansible_os_family == "RedHat"


- block:

    - name: Make sure the folder exists
      file:
        path: /usr/local/share/ca-certificates
        state: directory

    # Note that the .crt is actually a .pem renamed
    - name: Copy the certificate
      copy:
        src: '{{ common_ca }}'
        dest: /usr/local/share/ca-certificates/{{ common_ca | basename }}.crt
      register: result

    - name: Update CA Trust
      command: update-ca-certificates
      when: result is changed

  when: ansible_os_family == "Debian"
