---

- name: install epel-release
  package:
    name: epel-release
  when: common_epel

- include: ca.yml
  when:
    - common_ca is defined
    - common_ca != ''

- name: install common packages
  package:
    name: '{{ common_packages }}'
  delay: 10
  retries: 3
  register: result
  until: result is succeeded
  when:
    - common_packages is defined
    - common_packages != ''
    - common_packages != []

- name: enable and start common services
  systemd:
    name: '{{ common_services }}'
    enabled: yes
    state: started
  when:
    - common_services is defined
    - common_services != ''
    - common_services != []
